### ISSUE TITLE
Slow wireless performance - 468 MBits/s MAX and high CPU usage

### ISSUE THREAD

**Issue by D35P4C1T0** [dalaoshi777/rm2100-lede-ci#1]
As title says, with this build I'm facing slower wireless performance compared to other firmwares, perhaps because they're using different wireless drivers.

Here's the CPU usage whilst running an iperf3 run between a wired client actis as a server and a wireless client acting as a client.

![Screenshot from 2022-08-16 13-49-24](https://user-images.githubusercontent.com/42818929/184873055-3130fd89-a9b1-405c-84b5-2e07c7908312.png)

I did not change any settings besides the wireless channel, the test was done on wifi5 (AC).

**Comment by dalaoshi777** [comment]
closed source drive
